//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Context_Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_Integration_Entity : DbContext
    {
        public object _obj;

        public Db_Integration_Entity()
            : base("name=Db_Integration_Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_company_information> m_company_information { get; set; }
        public virtual DbSet<m_state_information> m_state_information { get; set; }
        public virtual DbSet<m_city_information> m_city_information { get; set; }
        public virtual DbSet<m_cuntry_information> m_cuntry_information { get; set; }
    
        public virtual ObjectResult<Sushil_Result> Sushil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sushil_Result>("Sushil");
        }
    }
}
