//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Context_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_city_information
    {
        public int city_id { get; set; }
        public string city_name { get; set; }
    }
}
