//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Context_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_company_information
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string company_web_site { get; set; }
        public Nullable<int> company_country { get; set; }
        public Nullable<int> company_state { get; set; }
        public Nullable<int> company_city { get; set; }
        public string company_address_1 { get; set; }
        public string company_address_2 { get; set; }
        public string company_poster_code { get; set; }
        public string company_pan { get; set; }
        public string compay_tax { get; set; }
        public string company_gst { get; set; }
        public string company_cst { get; set; }
        public string comany_bst_no { get; set; }
        public string company_fax_no { get; set; }
        public string company_phone { get; set; }
        public string company_email_id { get; set; }
        public Nullable<int> devloper_id { get; set; }
        public string ac_flag { get; set; }
    }
}
